kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-log-analysis-deployment
spec:
  selector:
    matchLabels:
      run: app-log-analysis
  replicas: 2
  template:
    metadata:
      labels:
        run: app-log-analysis
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: app-log-analysis
          image: icr.io/solution-tutorials/tutorial-application-log-analysis
---
kind: Service
apiVersion: v1
metadata:
  name: app-log-analysis-svc
  labels:
    run: app-log-analysis
spec:
  type: NodePort
  ports:
    - port: 8001
      protocol: TCP
  selector:
    run: app-log-analysis
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-log-analysis-ingress
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  rules:
  - host: $MYINGRESSSUBDOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-log-analysis-svc
            port:
              number: 8001
# for older clusters, you can uncomment the deprecated Ingress syntax
# and comment the Ingress definition above
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: app-log-analysis-ingress
# spec:
#   rules:
#   - host: $MYINGRESSSUBDOMAIN
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: app-log-analysis-svc
#           servicePort: 8001
